"""GenBank flat file format export for gene + primer pairs.

Generates a .gb file containing:
- LOCUS line with gene name and sequence length
- FEATURES section with gene, CDS, and primer_bind annotations
- ORIGIN section with the full template sequence
"""

from datetime import datetime
from typing import Dict, List, Optional

from .primer_design import PrimerPair
from .gff_index import TranscriptRecord, GeneRecord


def _current_date() -> str:
    return datetime.now().strftime("%d-%b-%Y").upper()


def _wrap_origin(sequence: str, width: int = 60) -> str:
    """Format sequence into GenBank ORIGIN blocks.

    Groups of 10 bases, 6 groups per line (60 bases per line).
    """
    lines = ["ORIGIN"]
    seq_len = len(sequence)
    for chunk_start in range(0, seq_len, width):
        chunk = sequence[chunk_start:chunk_start + width]
        parts = []
        for i in range(0, len(chunk), 10):
            parts.append(chunk[i:i + 10].lower())
        line_num = chunk_start + 1
        lines.append(f"{line_num:>9} " + " ".join(parts))
    lines.append("//")
    return "\n".join(lines)


def export_genbank(
    gene_name: str,
    gene_record: GeneRecord,
    transcript: TranscriptRecord,
    template_sequence: str,
    pairs: List[PrimerPair],
    specificity_results: Optional[list] = None,
    include_cdna: bool = True,
    cdna_info: Optional[List[dict]] = None,
    annotation: Optional[dict] = None,
) -> str:
    """Generate a GenBank flat file for a gene with primer annotations.

    Args:
        gene_name: Short gene name (e.g. "Glyma.13G357600").
        gene_record: GeneRecord from GFF3.
        transcript: TranscriptRecord with exon/CDS info.
        template_sequence: Full genomic template sequence used for primer design.
        pairs: List of designed PrimerPair objects.
        specificity_results: Optional list of SpecificityResult objects.
        include_cdna: Whether to include cDNA (spliced) sequence as a feature note.
        cdna_info: Optional list of cDNA amplicon dicts per pair (from transcript_seq).

    Returns:
        GenBank flat file text.
    """
    seq_len = len(template_sequence)
    date_str = _current_date()

    lines = []

    # LOCUS
    locus_name = gene_name[:16].replace(".", "_")
    molecule_type = "DNA" if not transcript.cds_exons else "mRNA"
    topology = "linear"
    division = "PLN"  # Plant
    lines.append(
        f"LOCUS       {locus_name:<16} {seq_len:>7} bp    "
        f"{molecule_type:<5}     {topology:<5} {division} {date_str}"
    )

    # DEFINITION
    definition_parts = [f"Glycine max {gene_name}"]
    if annotation:
        gene_symbol = annotation.get("gene_name", "")
        ath = annotation.get("arabidopsis_homolog", "")
        if gene_symbol:
            definition_parts.append(f"({gene_symbol})")
        if ath:
            definition_parts.append(f"Arabidopsis homolog: {ath}")
    definition_parts.append("with PCR primer binding sites.")
    lines.append(f"DEFINITION  {' '.join(definition_parts)}")

    # ACCESSION
    lines.append(f"ACCESSION   {gene_name}")

    # VERSION
    lines.append(f"VERSION     {gene_name}")

    # KEYWORDS
    lines.append("KEYWORDS    primer; PCR; soybean.")

    # SOURCE
    lines.append("SOURCE      Glycine max (soybean) cultivar Williams 82")
    lines.append("  ORGANISM  Glycine max")
    lines.append("            Eukaryota; Viridiplantae; Streptophyta; Embryophyta;")
    lines.append("            Tracheophyta; Spermatophyta; Magnoliopsida; eudicotyledons;")
    lines.append("            Gunneridae; Pentapetalae; rosids; fabids; Fabales;")
    lines.append("            Fabaceae; Papilionoideae; Phaseoleae; Glycine.")

    # REFERENCE
    lines.append("REFERENCE   1  (bases 1 to " + str(seq_len) + ")")
    lines.append("  AUTHORS   Generated by Soybean Primer-BLAST v1.0")
    lines.append(f"  JOURNAL   Unpublished, {date_str}")
    lines.append("REFERENCE   2  (bases 1 to " + str(seq_len) + ")")
    lines.append("  AUTHORS   Schmutz,J., Cannon,S.B., Schlueter,J., Ma,J., et al.")
    lines.append("  TITLE     Genome sequence of the palaeopolyploid soybean")
    lines.append("  JOURNAL   Nature 463 (7278), 178-183 (2010)")
    lines.append("  PUBMED    20075913")

    # FEATURES
    lines.append("FEATURES             Location/Qualifiers")

    # Source feature
    lines.append(f"     source          1..{seq_len}")
    lines.append(f'                     /organism="Glycine max"')
    lines.append(f'                     /cultivar="Williams 82"')
    lines.append(f'                     /chromosome="{gene_record.seqid}"')
    lines.append(f'                     /mol_type="genomic DNA"')

    # Gene feature (template-local coordinates, 1-based)
    gene_start_tpl = 1
    gene_end_tpl = seq_len
    lines.append(f"     gene            {gene_start_tpl}..{gene_end_tpl}")
    lines.append(f'                     /gene="{gene_name}"')
    if annotation:
        func = annotation.get("function_desc", "")
        if func and len(func) < 200:
            lines.append(f'                     /function="{func}"')
        ath = annotation.get("arabidopsis_homolog", "")
        if ath:
            lines.append(f'                     /note="Arabidopsis homolog: {ath}"')

    # mRNA
    lines.append(f"     mRNA            {gene_start_tpl}..{gene_end_tpl}")
    lines.append(f'                     /product="{gene_name} transcript"')

    # CDS features from GFF3, mapped to template-local coords
    if transcript.cds_exons:
        for cds_start, cds_end in transcript.cds_exons:
            if transcript.strand == "+":
                tpl_start = cds_start - transcript.start + 1
                tpl_end = cds_end - transcript.start + 1
            else:
                tpl_start = transcript.end - cds_end + 1
                tpl_end = transcript.end - cds_start + 1
            tpl_start = max(1, min(seq_len, tpl_start))
            tpl_end = max(1, min(seq_len, tpl_end))

            if tpl_start <= tpl_end:
                lines.append(f"     CDS             {tpl_start}..{tpl_end}")
                lines.append(f'                     /gene="{gene_name}"')
                lines.append(f'                     /codon_start=1')

    # Exon features
    exons = transcript.all_exons or transcript.cds_exons
    for i, (ex_start, ex_end) in enumerate(exons):
        if transcript.strand == "+":
            tpl_start = ex_start - transcript.start + 1
            tpl_end = ex_end - transcript.start + 1
        else:
            tpl_start = transcript.end - ex_end + 1
            tpl_end = transcript.end - ex_start + 1
        tpl_start = max(1, min(seq_len, tpl_start))
        tpl_end = max(1, min(seq_len, tpl_end))

        if tpl_start <= tpl_end:
            lines.append(f"     exon            {tpl_start}..{tpl_end}")
            lines.append(f'                     /number={i + 1}')
            lines.append(f'                     /gene="{gene_name}"')

    # Primer binding sites
    for i, pair in enumerate(pairs):
        pair_id = f"pair_{i + 1}"

        # Forward primer
        left_start = pair.left_position + 1
        left_end = pair.left_position + len(pair.left_primer)
        lines.append(f"     primer_bind     {left_start}..{left_end}")
        lines.append(f'                     /label="{pair_id}_forward"')
        lines.append(f'                     /note="Forward primer; Tm={pair.left_tm:.1f}C; GC={pair.left_gc:.1f}%"')

        # Reverse primer
        right_end_pos = pair.right_position + 1
        right_start_pos = pair.right_position - len(pair.right_primer) + 2
        # Primer3's right_position is the 3' end, so binding is upstream
        # For + strand: right_position is the 3' end; the primer binds from right_end- to right_position

        # Actually, for a standard annotation: primer_bind on the minus strand
        # Primer3 reports right_position as 0-based coordinate of the 5' end
        # of the right primer on the template. Let me use the convention:
        # right primer binds from (right_position+1) to (right_position+len(right_primer))
        right_5prime = pair.right_position + 1
        right_3prime = pair.right_position + len(pair.right_primer)
        lines.append(f"     primer_bind     complement({right_5prime}..{right_3prime})")
        lines.append(f'                     /label="{pair_id}_reverse"')
        lines.append(f'                     /note="Reverse primer; Tm={pair.right_tm:.1f}C; GC={pair.right_gc:.1f}%"')

        # Specificity note
        if specificity_results and i < len(specificity_results):
            sr = specificity_results[i]
            if sr.is_specific:
                lines.append(f'     primer_bind     note="Specificity: PASS"')
            else:
                lines.append(f'     primer_bind     note="Specificity: FAIL ({sr.off_target_count} off-target)"')
                for amplicon in sr.off_target_amplicons[:5]:
                    gene_note = f" gene={amplicon.gene_name}" if amplicon.gene_name else ""
                    lines.append(
                        f'     primer_bind     note="  Off-target: {amplicon.chromosome} '
                        f'({amplicon.product_size}bp){gene_note}"'
                    )

        # cDNA amplicon
        if cdna_info and i < len(cdna_info) and cdna_info[i]:
            cdna = cdna_info[i]
            lines.append(f'     primer_bind     note="cDNA amplicon: {cdna["cdna_length"]}bp '
                         f'[{cdna["left_cdna_position"] + 1}..{cdna["right_cdna_position"] + 1}]"')

    # ORIGIN
    lines.append(_wrap_origin(template_sequence))

    return "\n".join(lines)


def export_genbank_multi_gene(
    results: List[dict],
) -> str:
    """Generate a single GenBank file containing multiple gene+primer entries.

    Args:
        results: List of dicts, each with keys:
            gene_name, gene_record, transcript, template_sequence,
            pairs, specificity_results (optional), cdna_info (optional),
            annotation (optional)

    Returns:
        Concatenated GenBank text (entries separated by blank lines).
    """
    parts = []
    for i, entry in enumerate(results):
        gb = export_genbank(
            gene_name=entry.get("gene_name", f"gene_{i+1}"),
            gene_record=entry["gene_record"],
            transcript=entry["transcript"],
            template_sequence=entry["template_sequence"],
            pairs=entry.get("pairs", []),
            specificity_results=entry.get("specificity_results"),
            cdna_info=entry.get("cdna_info"),
            annotation=entry.get("annotation"),
        )
        parts.append(gb)
    return "\n\n".join(parts)
